version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cp .env.production .env
      - npm install
  build:
    commands:
      - ls -al 
      - npm run generate
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths '/*'
cache:
  paths:
    - 'node_modules/**/*'
