version: 0.2
env:
  AWS_DEFAULT_REGION: ap-northeast-2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # 내 ecr base 사용.
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cp .env.production .env
      - npm install
      - pwd
      - ls -al
  build:
    commands:
      - npm run generate
  post_build:
    commands:
      - aws s3 sync ./dist s3://${S3_BUCKET} 
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths '/*'
cache:
  paths:
     - 'node_modules/**/*'
